# Generated by Django 4.0.5 on 2022-07-03 17:35

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_productimage_review_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/products/images', validators=[store.validators.validate_image_size]),
        ),
    ]
