version: '3.9'
services:
  web:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - .:/app
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=store
      - MYSQL_ROOT_PASSWORD=0000
    volumes:
      - mysqldata:/var/lib/mysql   